version: ~> 1.0

language: scala

env:
  matrix:
    - TRAVIS_JDK=11

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version

stages:
  - name: validate
  - name: docs
  - name: jacoco
  - name: test
  - name: deploy
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:

    - stage: validate
      name: "Validate code"
      script: sbt scalafmtCheckAll +mimaReportBinaryIssues
      env: TRAVIS_JDK=11

    - stage: docs
    - script: cd docs && sbt validateDocs evaluateSbtFiles
      name: "Validate docs, Evaluate sbt files JDK 8"
      env: TRAVIS_JDK=8
    - script: cd docs && sbt validateDocs evaluateSbtFiles
      name: "Validate docs, Evaluate sbt files JDK 11"
      env: TRAVIS_JDK=11

    - stage: jacoco
      script: sbt +jacoco
      env: TRAVIS_JDK=8
      name: "Jacoco JDK8"
    - env: TRAVIS_JDK=11
      name: "Jacoco JDK11"
      script: sbt +jacoco

    - stage: test
    - script: sbt +publishLocal +plugin/test +plugin/scripted
      name: "Test plugins JDK 8"
      env: TRAVIS_JDK=8
    - script: sbt +publishLocal +plugin/test +plugin/scripted
      name: "Test plugins JDK11"
      env: TRAVIS_JDK=11

    - stage: deploy
      name: "Publish artifacts to Bintray"
      script: sbt +publish
      env: TRAVIS_JDK=11

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.coursier/cache
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
